from typing import Any, Dict, List, Optional
from kernel.process import ProcessControlBlock
from kernel.governor import ResourceGovernor
from syscalls import SyscallRegistry
from models.provider import BaseModelProvider
from memory.mmu import MemoryManagementUnit
from agents.base_agent import BaseAgent

DEFAULT_REVIEWER_PROMPT = (
    "You are a specialized Reviewer and Auditor Agent inside AI-OS. Your role is to inspect code, "
    "test outputs, and data artifacts generated by other agents. Verify correctness against formal specifications, "
    "identify security vulnerabilities or regressions, and issue structured pass/fail audit verdicts using the sys_audit_record_verdict syscall."
)

class ReviewerAgent(BaseAgent):
    """
    Specialized Reviewer / Auditor Agent.
    Validates outputs against specifications, inspects code artifacts, and issues
    formal review approvals or rejections.
    """
    def __init__(
        self,
        pcb: ProcessControlBlock,
        system_prompt: Optional[str] = None,
        model_provider: Optional[BaseModelProvider] = None,
        syscall_registry: Optional[SyscallRegistry] = None,
        governor: Optional[ResourceGovernor] = None,
        mmu: Optional[MemoryManagementUnit] = None,
        model_router: Optional[Any] = None
    ):
        prompt = system_prompt or DEFAULT_REVIEWER_PROMPT
        super().__init__(
            pcb=pcb,
            system_prompt=prompt,
            model_provider=model_provider,
            syscall_registry=syscall_registry,
            governor=governor,
            mmu=mmu,
            model_router=model_router
        )
        self.verdicts: List[Dict[str, Any]] = []

    def record_verdict(self, target_pid: str, approved: bool, comments: str) -> Dict[str, Any]:
        """Record a structured verification verdict in the reviewer's local audit log and blackboard."""
        verdict = {
            "target_pid": target_pid,
            "approved": approved,
            "comments": comments,
            "auditor_pid": self.pcb.pid
        }
        self.verdicts.append(verdict)
        if hasattr(self, "syscalls") and getattr(self.syscalls, "kernel", None):
            kernel = self.syscalls.kernel
            if hasattr(kernel, "blackboard"):
                kernel.blackboard.write("system_audit", f"verdict_{target_pid}", verdict, author_pid=self.pcb.pid)
        return verdict
